version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Build started on `date`
      - mvn package -DskipTests=true
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/auth-server.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes